version: '3'
services:
  postgres:
    image: postgres:11
    environment:
      - POSTGRES_PASSWORD=password
  nginx:
    image: nginx:1.17.5-alpine
    volumes:
      - media:/usr/share/nginx/html
    ports:
      - 127.0.0.1:8080:80
  kobra:
    build: .
    environment:
      - SECRET_KEY=yourOwnSecretKey
      - STORAGE_PATH=/srv/media
      - DATABASE_URL=postgres://postgres:password@postgres:5432/kobra
      - WAIT_FOR=tcp://postgres:5432
    volumes:
      - media:/srv/media
    ports:
      - 127.0.0.1:3000:3000
    depends_on:
      - postgres
  # mysql:
  #   image: mysql:8.0
  #   environment:
  #     - MYSQL_ROOT_PASSWORD=password
  #     - MYSQL_DATABASE=kobra
  #   command: ["--default-authentication-plugin=mysql_native_password"]
  # kobra:
  #   build: .
  #   environment:
  #     - SECRET_KEY=yourOwnSecretKey
  #     - DATABASE_URL=mysql2://root:password@mysql:3306/kobra?pool=5
  #     - WAIT_FOR=tcp://mysql:3306
  #   ports:
  #     - 127.0.0.1:3000:3000
  #   depends_on:
  #     - mysql

volumes:
  media: